# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove-cli" do
  name "grove-cli"
  desc "Zero-friction worktree management for developers"
  homepage "https://github.com/LeahArmstrong/grove-cli"
  version "0.1.0"

  livecheck do
    url "https://github.com/LeahArmstrong/grove-cli/releases"
    strategy :github_latest
  end

  binary "grove"

  on_macos do
    on_intel do
      url "https://github.com/LeahArmstrong/grove-cli/releases/download/v#{version}/grove-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "f794627e13cd2a1da016fe058c235126c05cacc1f1d6967f1d74c0131b3b6b39"
    end
    on_arm do
      url "https://github.com/LeahArmstrong/grove-cli/releases/download/v#{version}/grove-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "ee23469b0156aeb1fa74ef8e1fce2b48905df41c38b09e199088eb822d61e314"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LeahArmstrong/grove-cli/releases/download/v#{version}/grove-cli_#{version}_linux_amd64.tar.gz"
      sha256 "879b4b18c1d79fb54c8b1153bea4e35f19390f6c7dfc82363de1e3ebc06cb1af"
    end
    on_arm do
      url "https://github.com/LeahArmstrong/grove-cli/releases/download/v#{version}/grove-cli_#{version}_linux_arm64.tar.gz"
      sha256 "2cd4a63c591d43f3d26e269c85d69c3ca77519302a2cd34933fa44bc767c2c25"
    end
  end

  caveats <<~EOS
    To enable grove, add this to your shell configuration:

    For zsh (~/.zshrc):
      eval "$(grove init zsh)"

    For bash (~/.bashrc):
      eval "$(grove init bash)"

    Then reload your shell:
      source ~/.zshrc  # or ~/.bashrc
  EOS

  # No zap stanza required
end
